name = "picgo-worker"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[vars]
FORMAT = "{year}/{month}/{day}/{md5}.{extName}"

[observability]
enabled = true

[placement]
mode = "smart"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "picgo-worker"
