name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        env:
          TOKEN: ${{ secrets.TOKEN }}
          BUCKET_URL: ${{ secrets.BUCKET_URL}}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          environment: production
